# Acquia Build Steps Definitions

build-steps:
  - composer-update:
      script:
        - "composer install"
        - "composer update"
      type: script
  - post-build:
      script:
        - "chmod 755 %SOURCE_DIR%"
      type: script
